spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: guest
    password: guest

  mail:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          starttls:
            enable: true

  application:
    name: ${SERVER_HOST}

server:
  port: ${SERVER_PORT}
